### ISSUE TITLE
【已解决】你好，关于怎么使用离线地图的几个问题。（包含简易手册说明离线地图使用方式

### ISSUE THREAD

**Issue by YuanBo1996** [zlq4863947/pz-webmap#6]
我已经下载的pz-webmap也安装了Node.js
可打开Node.js后是一个CMD的界面，我应该输入什么指令来打开离线地图？

**Comment by CodeWarriors0** [comment]
在完成电脑安装 Node.js的基础上完成以下步骤:
1、下载这个项目到你自己电脑上
2、用CMD界面进入此项目文件夹
3、输入命令 【npm install】
4、依照提示 输入 【npm audit fix】如果没有提示输入此项可以直接跳过
5、输入命令 【npm start】 
6、CMD界面出现以下提示则启动成功
http-server .

Starting up http-server, serving .
Available on:
  http://xxx.xxx.xxx.xxx:8080
  http://127.0.0.1:8080
Hit CTRL-C to stop the server

7、在浏览器中输入【127.0.0.1:8080】即可访问项目

**Comment by YuanBo1996** [comment]
> 在完成电脑安装Node.js的基础上完成以下步骤：
> 1，下载这个项目到你自己的电脑上
> 2，用CMD界面进入此项目文件夹
> 3，输入命令【npm install】
> 4，进行提示输入【npm audit解决方法：如果没有提示输入此可以直接跳过
> 5，输入命令【npm start】
> 6，CMD接口出现以下提示则启动成功
> http-server。
> 
> 启动http-server，服务。
> 可用于：
> [http](http://xxx.xxx.xxx.xxx:8080) : [//xxx.xxx.xxx.xxx](http://xxx.xxx.xxx.xxx:8080) :
> [8080 http://127.0.0.1:8080](http://127.0.0.1:8080)
> 按下CTRL-C来停止服务器
> 
> 7，在浏览器中输入【127.0.0.1:8080】即可访问项目

Node.js
我输入C:\Users\Hasee\Downloads\pz-webmap-master后
提示 ↓
uncaught SyntaxError：Invalid or unexpected token
该怎么解决？_(:з」∠)_代码小白，虽然能看懂一部分你说的，但是报错该怎么解决就懵逼了。

**Comment by CodeWarriors0** [comment]
很抱歉我也不是很清楚为什么你会出现这个错误，但我抽空录制了一个GIF图。
你可以按照这个GIF参照自己的操作步骤，希望能帮到你!
![2](https://user-images.githubusercontent.com/48375544/112604399-0efeb200-8e51-11eb-8fcb-1aee5565c2fd.gif)

**Comment by zlq4863947** [comment]
@YuanBo1996  `uncaught SyntaxError：Invalid or unexpected token` 这个错误的全部信息不贴出来，别人没法知道你那边的详细错误

**Comment by YuanBo1996** [comment]
> @ YuanBo1996 `uncaught SyntaxError：Invalid or unexpected token`这个错误的全部信息不贴出来，别人没法知道你那边的详细错误

上个月上班忙，现在才翻墙看到，怪不得不对，上面gif的操作里是直接通过CMD输入指令的，我理解成Node.js输入指令，所以报错就是你看到的这句话。从GitHub下载的文件，压缩包里并没有GIF图里的“trunk”文件夹。不知道这一步我该怎么解决？

**Comment by CodeWarriors0** [comment]
我猜你是用的github得直接下载功能下载的压缩包，存在如下图文件的就是trunk文件夹，注意看我的动图里面的文件有哪些你就能找到
![Snipaste_2021-04-15_11-56-38](https://user-images.githubusercontent.com/48375544/114812212-1ecf3d80-9de2-11eb-9130-fff37be70e3b.png)

**Comment by YuanBo1996** [comment]
> 我猜你是用的github得直接下载功能下载的压缩包，存在如下图文件的就是trunk文件夹，注意看我的动图里面的文件有什么你可以找到
> ![Snipaste_2021-04-15_11-56-38](https://user-images.githubusercontent.com/48375544/114812212-1ecf3d80-9de2-11eb-9130-fff37be70e3b.png)

感谢问题已解决。
给后人留个简易说明手册



前置【node.js】
“运行”“CMD”进入后
输入“CD （离线地图解压缩后的所在文件夹，包含盘符）”或直接进入离线地图解压缩后的所在文件夹在上方输入“CMD”来打开CMD
打开后
输入“npm install”
加载完成后
输入“npm audit fix”
弹出提示后
输入“npm start”
根据cmd 的IP提示进入指定IP网页查看离线地图
